class AddDataToSeats < ActiveRecord::Migration[6.0]
  def change
    Seat.create(:name => "A1", :category_id => 1)
    Seat.create(:name => "A2", :category_id => 1)
    Seat.create(:name => "A3", :category_id => 1)
    Seat.create(:name => "A4", :category_id => 1)
    Seat.create(:name => "A5", :category_id => 1)
    Seat.create(:name => "A6", :category_id => 1)
    Seat.create(:name => "A7", :category_id => 1)
    Seat.create(:name => "A8", :category_id => 1)
    Seat.create(:name => "A9", :category_id => 1)
    Seat.create(:name => "B1", :category_id => 2)
    Seat.create(:name => "B2", :category_id => 2)
    Seat.create(:name => "B3", :category_id => 2)
    Seat.create(:name => "B4", :category_id => 2)
    Seat.create(:name => "B5", :category_id => 2)
    Seat.create(:name => "B6", :category_id => 2)
    Seat.create(:name => "B7", :category_id => 2)
    Seat.create(:name => "B8", :category_id => 2)
    Seat.create(:name => "C1", :category_id => 3)
    Seat.create(:name => "C2", :category_id => 3)
    Seat.create(:name => "C3", :category_id => 3)
    Seat.create(:name => "C4", :category_id => 3)
    Seat.create(:name => "C5", :category_id => 3)
    Seat.create(:name => "C6", :category_id => 3)
    Seat.create(:name => "C7", :category_id => 3)
    Seat.create(:name => "C8", :category_id => 3)
    Seat.create(:name => "C9", :category_id => 3)
  end
end
